services:
  app:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./public/:/usr/share/nginx/html/public
      - ./build/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf